added httpcheck dashboard
lightstep/terraform-opentelemetry-dashboards pull request #101
Opened 2023-06-07 13:27 UTC by hecomp

## Description
What does this PR do?
added httpcheck dashboard

## PR checklist

Please confirm the following items:
- [] At least one screenshot of the proposed dashboard is included in this PR. If you're proposing substantive changes to queries or new queries then please ensure your screenshot shows relevant data.
- [] All chart names are in [Title case](https://en.wikipedia.org/wiki/Title_case).
- [] All query names are lower case letters, beginning the first query of each chart as "a" and proceeding alphabetically ... "b", "c", etcetera.

2023-09-13 03:21 UTC, nslaughter commented on collector-dashboards/otel-collector-httpcheck-dashboard/main.tf
> +    name = "HttpCheck Duration"
```suggestion
    name = "HTTPCheck Duration"
```

2023-09-13 03:21 UTC, nslaughter commented on collector-dashboards/otel-collector-httpcheck-dashboard/main.tf
> +    name = "Httpcheck Status Code"
```suggestion
    name = "HTTPcheck Status Code"
```

2023-09-13 03:21 UTC, nslaughter commented on collector-dashboards/otel-collector-httpcheck-dashboard/variables.tf
> +  description = "Name of Lightstep project"
```suggestion
  description = "Name of Cloud Observability project"
```

2023-09-13 03:22 UTC, nslaughter requested changes
Requested changes as suggestions

2023-09-14 21:25 UTC, hecomp commented
> Requested changes as suggestions

Addressed.

2023-09-19 12:13 UTC, merged