[DO NOT MERGE][LS-54353] otel-native kube comprehensive dashboard
lightstep/terraform-opentelemetry-dashboards pull request #142
Opened 2023-11-02 15:09 UTC by jdcrouse

**READ THIS FIRST**

this PR is for commenting only right now

this PR is not what will actually get merged. the real PR will include an entirely new file for this new dashboard type.

this PR is set up as changes to the existing file to highlight what is different between the two dashboards.

this doesnt need a ✅ 

## This PR
sets up a prebuilt LS dashboard for otel metrics to be useful for users that set up their collectors with the `kube-cloud-stack` helm chart

2023-11-02 15:09 UTC, jdcrouse commented on .pre-commit-config.yaml
> -      - id: tflint
ignore, this is because i cant commit anything without tflint failing for an unknown reason

2023-11-06 23:53 UTC, gdfast commented on .pre-commit-config.yaml
> -      - id: tflint
it's not just you. commit with `git commit --no-verify` to skip the precommit hooks. I'd love someone who owns this repo to fix it...

2023-11-07 18:08 UTC, djspoons commented on collector-dashboards/otel-collector-kubernetes-comprehensive-dashboard/main.tf
> +        query_string = "metric k8s.node.condition_ready | filter k8s.node.name == $node | latest | group_by [\"k8s.node.name\"], sum"
I'm not sure how big number is supposed to work when there is a group-by attribute... but this seems to always say "1" instead of total ("6").

2023-11-08 16:47 UTC, jdcrouse commented on collector-dashboards/otel-collector-kubernetes-comprehensive-dashboard-otel-native/main.tf
> +resource "lightstep_dashboard" "otel_collector_kubernetes_comprehensive_dashboard_otel_native" {
Q: Does the naming ("otel-native") make sense here? Should we name it something else? Should we change the existing dashboard to indicate that it uses prometheus convention metric names?

2023-11-08 16:47 UTC, jdcrouse commented on collector-dashboards/otel-collector-kubernetes-comprehensive-dashboard-otel-native/README.md
> +# Terraform Module for Lightstep OpenTelemetry Dashboards
TODO update this file

2023-11-08 16:48 UTC, jdcrouse commented on collector-dashboards/otel-collector-kubernetes-comprehensive-dashboard/main.tf
> +        query_string = "metric k8s.node.condition_ready | filter k8s.node.name == $node | latest | group_by [\"k8s.node.name\"], sum"
based on some other feedback i cut out the big number charts entirely in favor of graphs, so that solves this issue :-)

2023-11-08 17:18 UTC, gdfast commented on collector-dashboards/otel-collector-kubernetes-comprehensive-dashboard-otel-native/main.tf
> +resource "lightstep_dashboard" "otel_collector_kubernetes_comprehensive_dashboard_otel_native" {
Let's do the latter (change the existing dashboard to indicate that it uses prometheus convention metric names). I think the best approach for now is that users should assume that all of these dashboards work if they use the otel-cloud-stack charts, and we add some indicator like " (Prometheus)" in the title if this isn't the case.

Follow the example of the Host Metrics dashboards... there's one dashboard that's titled "Host Metrics" and another called "Host Metrics (Prometheus)". They also have descriptions that explain the situations where they will work.

2023-11-08 19:51 UTC, jdcrouse commented on collector-dashboards/otel-collector-kubernetes-comprehensive-dashboard-otel-native/main.tf
> +resource "lightstep_dashboard" "otel_collector_kubernetes_comprehensive_dashboard_otel_native" {
updated with that change => resolving

2023-11-08 20:12 UTC, jdcrouse commented on collector-dashboards/otel-collector-kubernetes-comprehensive-dashboard-prometheus/main.tf
> +terraform {
this is the old dashboard renamed

2023-11-08 20:29 UTC, gdfast commented on collector-dashboards/otel-collector-kubernetes-comprehensive-dashboard-otel-native/README.md
> +# Terraform Module for Lightstep OpenTelemetry Dashboards
run `make ready` in the repo root to update this file along with the top-level `main.tf` and `outputs.tf`. This might result in some changes unrelated to your dashboard change that you probably want to undo

2023-11-08 20:32 UTC, gdfast commented on collector-dashboards/otel-collector-kubernetes-comprehensive-dashboard-prometheus/README.md
> +This dashboard uses metrics with Prometheus semantic convention naming.
Regarding
> outputted by the OpenTelemetry collectors set up with the `otel-cloud-stack` collector config
I don't think this is quite right. The prometheus flavor of this dashboard is for when customers aren't using otel-cloud-stack and instead are scraping kubernetes metrics via a prometheus receiver. (It might be a good idea to check with someone like Clay or Jacob to see if I spelled that out correctly.)

2023-11-08 20:38 UTC, jdcrouse commented on collector-dashboards/otel-collector-kubernetes-comprehensive-dashboard-prometheus/README.md
> +This dashboard uses metrics with Prometheus semantic convention naming.
yup youre right good call

2023-11-08 20:39 UTC, jdcrouse commented on outputs.tf
> +  description = "Cloud Observability OpenTelemetry OpenTelemetry Airflow Integration Dashboard"
all of these added a second instance of the word "OpenTelemetry" when i ran `make ready` and i have no idea why

2023-11-08 20:54 UTC, gdfast requested changes

2023-11-08 20:54 UTC, gdfast commented on main.tf
> +      version = "~> 1.84.1"
this shouldn't have changed. make sure you git pull rebase the latest code from `main` onto your branch and then try running `make ready` again. beware that you might hit a git conflict here when doing this

2023-11-08 20:54 UTC, gdfast commented on collector-dashboards/otel-collector-kubernetes-comprehensive-dashboard/README.md
> -This is a Terraform module for deploying dashboards to monitor a Kubernetes cluster running an OpenTelemetry Collector scraping kube-state-metrics.
the part about this dashboard applying to "a Kubernetes cluster running an OpenTelemetry Collector scraping kube-state-metrics" is useful and would be good to keep in the _collector-dashboards/otel-collector-kubernetes-comprehensive-dashboard-prometheus/README.md_ file

2023-11-08 20:54 UTC, gdfast commented on outputs.tf
> +}
did we lose an ending newline?

2023-11-08 20:54 UTC, gdfast commented on outputs.tf
> +  description = "Cloud Observability OpenTelemetry K8s OpenTelemetry Collectors Dashboard"
this shouldn't have changed in your PR... i think this is another sign you need to pull and rebase the latest code

2023-11-08 20:57 UTC, gdfast commented on outputs.tf
> +  description = "Cloud Observability OpenTelemetry OpenTelemetry Airflow Integration Dashboard"
I bet there's also a lot of "Dashboard Dashboard" in there too?

my understanding is that the scripts that `make ready` runs prepends "OpenTelemetry" to the beginning of the dashboard title and adds "Dashboard" to the end when forming this description. so if the dashboard is already titled "OpenTelemetry <Component> Dashboard" you end up with "OpenTelemetry OpenTelemetry <Component> Dashboard Dashboard" which... is not nice.

I actually was "hand"-fixing these after I ran `make ready`, but fixing these module descriptions probably isn't worth it

2023-11-08 21:00 UTC, jdcrouse commented on main.tf
> +      version = "~> 1.84.1"
done already !

2023-11-08 21:00 UTC, jdcrouse commented on outputs.tf
> +  description = "Cloud Observability OpenTelemetry OpenTelemetry Airflow Integration Dashboard"
also just undid these changes and pushed a fix

2023-11-08 21:20 UTC, gdfast commented on collector-dashboards/otel-collector-kubernetes-comprehensive-dashboard/main.tf
>    dashboard_name        = "OpenTelemetry Collector Comprehensive Kubernetes Dashboard"
for both this revamped dashboard and the old dashboard, I think it would be good to remove the "OpenTelemetry Collector" part from the title, I think it's a waste of space and implies that this is monitoring Otel collectors (which it isn't)

2023-11-08 21:21 UTC, jdcrouse commented on collector-dashboards/otel-collector-kubernetes-comprehensive-dashboard/main.tf
>    dashboard_name        = "OpenTelemetry Collector Comprehensive Kubernetes Dashboard"
makes sense especially given that every dashboard in this repo is related to otel collectors

2023-11-08 21:22 UTC, gdfast commented on collector-dashboards/otel-collector-kubernetes-comprehensive-dashboard/main.tf
>    dashboard_description = "A comprehensive dashboard for monitoring Kubernetes clusters using the OpenTelemetry Collector."
It would be really helpful if this description included the list of receivers that a user should have configured in order to get the metrics that power this dashboard. Check out the "Host Metrics" and "Host Metrics (Prometheus)" dashboards for a decent example of this.

Most users won't actually directly use these Terraform modules, they'll instead use the dashboards from the prebuilt dashboard library, so even more important to add useful info in the dashboard descriptions than it is to add it to the README.md's here

2023-11-08 21:27 UTC, gdfast commented on collector-dashboards/otel-collector-kubernetes-comprehensive-dashboard-prometheus/README.md
> +This is a Terraform resource for a dashboard that monitors a Kubernetes cluster running an OpenTelemetry Collector scraping kube-state-metrics.
```suggestion
This is a Terraform resource for a dashboard that monitors a Kubernetes cluster running an OpenTelemetry Collector that scrapes [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics) with a [prometheus receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/prometheusreceiver).
```

2023-11-08 21:28 UTC, gdfast commented
Couple extra notes
* The directory with your new dashboard seems to be missing its `outputs.tf` and `variables.tf` files
* I noticed in your linked dashboard that the "Cluster Overview" section moved from the top to the bottom. Is there a reason for that?  I'd expect to see it at the top

2023-11-08 21:33 UTC, jdcrouse commented
> The directory with your new dashboard seems to be missing its outputs.tf and variables.tf files
They exist, they are just entirely unchanged from before (since the new dashboard is in the "old" dashboard's original directory) https://github.com/lightstep/terraform-opentelemetry-dashboards/tree/jason/otel-native-kube-comprehensive/collector-dashboards/otel-collector-kubernetes-comprehensive-dashboard

2023-11-08 21:35 UTC, jdcrouse commented
> I noticed in your linked dashboard that the "Cluster Overview" section moved from the top to the bottom. Is there a reason for that? I'd expect to see it at the top
IMO that group isn't really that useful for monitoring or debugging, it seems like some of the least important information to look at in real time (i.e. is the number of namespaces the most important first thing to see when checking the health of my clusters?)

but i could be convinced otherwise

2023-11-08 22:24 UTC, gdfast commented
> > I noticed in your linked dashboard that the "Cluster Overview" section moved from the top to the bottom. Is there a reason for that? I'd expect to see it at the top
> 
> IMO that group isn't really that useful for monitoring or debugging, it seems like some of the least important information to look at in real time (i.e. is the number of namespaces the most important first thing to see when checking the health of my clusters?)
> 
> but i could be convinced otherwise

well, I don't think the dashboard really says all that much about health, it's more about what resources exist and what's happening. The reason I figured that cluster would be at the top is because there's sort of a hierarchy of resources in k8s. At the highest level there's a Cluster. A cluster has a Control Plane (which has etcd, and a scheduler and other things. A cluster also has Nodes. The nodes container kubelets and pods. etc etc. See https://kubernetes.io/docs/concepts/overview/components/. But I guess it doesn't matter too much with this dashboard

2023-11-08 22:25 UTC, gdfast commented
> > The directory with your new dashboard seems to be missing its outputs.tf and variables.tf files
> 
> They exist, they are just entirely unchanged from before (since the new dashboard is in the "old" dashboard's original directory) https://github.com/lightstep/terraform-opentelemetry-dashboards/tree/jason/otel-native-kube-comprehensive/collector-dashboards/otel-collector-kubernetes-comprehensive-dashboard

ahh got it, thanks. It's an inherently confusing diff

2023-11-08 22:26 UTC, gdfast approved these changes

2023-11-09 16:26 UTC, merged