LS-58504 update generaterootmod to no longer hard code provider version
lightstep/terraform-opentelemetry-dashboards pull request #149
Opened 2024-01-25 15:51 UTC by adil-sultan

## Description
This PR updates generaterootmod so that it programmatically pulls the required_providers version from the modules when generating the root main.tf. 

This should be safe to pull from any module in` /collector-dashboards` since dependabot will keep all the modules versions in sync.

Also updates the makefile which had an issue with tflint not running as expected recursively.

## PR checklist

Please confirm the following items:
The checklist below does not apply, I tested this out locally by running `make ready` and ensuring the root files appeared as expected.

- [ ] At least one screenshot of the proposed dashboard is included in this PR. If you're proposing substantive changes to queries or new queries then please ensure your screenshot shows relevant data.
- [ ] All chart names are in [Title case](https://en.wikipedia.org/wiki/Title_case).
- [ ] All query names are lower case letters, beginning the first query of each chart as "a" and proceeding alphabetically ... "b", "c", etcetera.

2024-01-25 16:07 UTC, jdcrouse commented on outputs.tf
> -  description = "Cloud Observability OpenTelemetry Airflow Integration Dashboard"
i ran into this auto generate bug a while bag and i cant remember exactly why it happened or how i fixed it, but lemme see if i can find out

2024-01-25 16:08 UTC, jdcrouse commented on outputs.tf
> -  description = "Cloud Observability OpenTelemetry Airflow Integration Dashboard"
found it, lookslike i just undid them by hand too https://github.com/lightstep/terraform-opentelemetry-dashboards/pull/142#discussion_r1387191163

2024-01-25 16:11 UTC, adil-sultan commented on outputs.tf
> -  description = "Cloud Observability OpenTelemetry Airflow Integration Dashboard"
I'm thinking I can either remove 'OpenTelemetry' from being part of the prefix or I can remove them from the dashboard modules. Lmk if there's a preference, I don't feel strongly either way

2024-01-25 16:28 UTC, adil-sultan commented on outputs.tf
> -  description = "Cloud Observability OpenTelemetry Airflow Integration Dashboard"
I'm in here might as well do it the right way. I removed OpenTelemetry from the modules since they'll get prefxed anyways.

2024-01-25 17:10 UTC, gdfast requested changes

2024-01-25 17:10 UTC, gdfast commented on tools/generaterootmod.go
> +func getRequiredProvidersVersion(dirPath string) (string, error) {
Clean Code nit: helper functions should be defined below the function that calls it

2024-01-25 17:10 UTC, gdfast commented on tools/generaterootmod.go
> +	writeMainHead(rootMain, "collector-dashboards")
given this argument is hardcoded and this function isn't used anywhere else, you might as well leave the function signature alone and set the directory path inside the `getRequiredProvidersVersion` function

```
func getRequiredProvidersVersion() (string, error) {
    const submoduleDirectoryPath string = "collector-dashboards"
    ...
```

2024-01-25 17:10 UTC, gdfast commented on outputs.tf
> +  description = "Cloud Observability OpenTelemetry OpenTelemetry / Host Metrics / Memory Dashboard"
doubled "OpenTelemetry OpenTelemetry"

2024-01-25 17:10 UTC, gdfast commented on outputs.tf
> +  description = "Cloud Observability OpenTelemetry OpenTelemetry kafkametricsreceiver Integration Dashboard"
doubled "OpenTelemetry OpenTelemetry"

2024-01-25 17:10 UTC, gdfast commented on outputs.tf
> +  description = "Cloud Observability OpenTelemetry OpenTelemetry Elasticsearchreceiver Receiver Dashboard"
doubled "OpenTelemetry OpenTelemetry"

2024-01-25 17:12 UTC, adil-sultan commented on collector-dashboards/otel-collector-hostmetrics-disk-dashboard/main.tf
> +  dashboard_name        = " Host Metrics / Disk"
Ah shoot I forgot to save these files and push them, will include with the rest of your recommended edits

2024-01-25 20:38 UTC, adil-sultan reviewed
@gdfast One thing to note is that the `make ready` currently returns a warning for the 'Otel-Collector-Dashboard' for an unused `variable dashboard_addons`. 

I didn't change this for the time being. Looks like it's an optional add on for prometheus receivers and it fits with the charts in the dashboard. If you'd like to see it removed, let me know.

2024-01-26 01:46 UTC, adil-sultan commented on outputs.tf
>    description = "Cloud Observability OpenTelemetry Kubernetes Dashboard"
This module has a odd quirk. It's 2 different modules in one and it's supposed to create a separate dashboard URL output per workload for one of them. It seemed like more work than was worth it at this time to separate them out so I just manually updated the name.

This is not an OOTB dashboard fwiw.

2024-01-26 18:55 UTC, gdfast reviewed
I did checked out this branch and ran `make ready` and hit two issues

First, it failed
```
% git co LS-58504-cleanup-root-mod-generator
% make ready

go run tools/generaterootmod.go
2024/01/26 13:52:36 open collector-dashboards/otel-collector-MY_DASHBOARD/main.tf: no such file or directory
exit status 1
make: *** [gen] Error 1
```

Second, it modified the repo root `main.tf` and `outputs.tf`

Am I missing something? I literally just checked out your branch, so I know I'm not behind.

2024-01-26 19:57 UTC, gdfast approved these changes

2024-01-26 21:42 UTC, merged