airflow dashboard
lightstep/terraform-opentelemetry-dashboards pull request #62
Opened 2023-04-11 23:23 UTC by altuner

<img width="1314" alt="Screen Shot 2023-04-11 at 4 22 10 PM" src="https://user-images.githubusercontent.com/4259308/231309398-f048aa43-804b-45a6-b48f-99d0c035d161.png">

2023-04-12 14:23 UTC, nslaughter requested changes
See comment inline about dashboard_description.
Also, chart titles should be title case.

2023-04-12 14:26 UTC, nslaughter commented on collector-dashboards/otel-collector-airflow-dashboard/main.tf
> +      query_string = "metric airflow.scheduler_heartbeat | rate | group_by [], sum"
I don't find this meaningful as a rate. I only care to see heartbeats as a binary status. The squiggles don't help. I'd go so far as to suggest dropping it.

2023-04-12 14:29 UTC, hecomp reviewed
LGTM. Just small comments.

2023-04-12 14:29 UTC, hecomp commented on collector-dashboards/otel-collector-airflow-dashboard/main.tf
> +      query_string = "metric airflow.dag_processing.processes | rate | group_by [], sum"
Add heredoc here and below `query_string`.

2023-04-12 14:29 UTC, hecomp commented on collector-dashboards/otel-collector-airflow-dashboard/main.tf
> +    name = "Scheduler heartbeat"
Add all starting caps. Ex:. `Scheduler Heartbeat`. Apply to below chart names.

2023-04-12 14:30 UTC, nslaughter requested changes
Sorry... didn't notice on my previous that most of these are `rate` and I believe that `delta` is more meaningful. The rate will show us count/interval. To me, the nature of this data is such that the unscaled values are more meaningful.

2023-04-12 19:16 UTC, hecomp commented on collector-dashboards/otel-collector-airflow-dashboard/main.tf
> +      query_string = "metric airflow.dag_processing.processes | rate | group_by [], sum"
> @hecomp are you sure we need it if it perfectly fits in one line?

I believe that Nathan mentioned about keeping consistent. But may be no need.

2023-05-12 21:12 UTC, nslaughter approved these changes

2023-05-12 21:12 UTC, merged